#Generator file info
taxo_depth: <taxo depth here>
item_depth: <item depth here>

myo_schemas:
    - <myo schemas here>

woo_schemas:
    - <woo schemas here>

fallback_schema: <fallback_schema here>

#File ID of generator file
gen_fid: <FID here>

#GIDs of each tab
gen_gid: <GID here>
dprc_gid: <GID here>
dprp_gid: <GID here>
spec_gid: <GID here>
us_gid: <GID here>
xs_gid: <GID here>

#OAuth credentials
oauth_client_id: <client ID here>
oauth_client_secret: <client secret here>

#Image Sources
imgFolder_glb: <img dir here>
imgFolder_extra: {
    schema: <extra img dir here>
}

# Location of webserver directory
web_folder: <web dir here>
